# Generated by Django 5.2.5 on 2025-08-28 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='supermarket',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
